const characters = {
"Mario": {
  image: "mario.png",
  weight: "98",
  weightClass: "Middleweight",
  archetype: "All-Rounder",
  combos: ['Up Air → Up Air', 'Down Throw → Fair'],
  oos: ["Up Smash"],
  killConfirms: ["Back Air, F-Smash"],
  recovery: "Add recovery notes here.",
  notes: ["Versatile toolkit."]
},
"Bowser": {
  image: "bowser.png",
  weight: "135",
  weightClass: "Super Heavy",
  archetype: "Heavyweight",
  combos: ['Up Throw → Fair', 'Nair → Dash Attack'],
  oos: ["Up B"],
  killConfirms: ["Side B, F-Tilt"],
  recovery: "Add recovery notes here.",
  notes: ["Kills very early."]
},
"Captain Falcon": {
  image: "captain_falcon.png",
  weight: "104",
  weightClass: "Heavy",
  archetype: "Rushdown",
  combos: ['Nair 1 → Knee', 'Down Throw → Fair'],
  oos: ["Up B"],
  killConfirms: ["Knee, Back Air"],
  recovery: "Add recovery notes here.",
  notes: ["Explosive punish game."]
},
"Donkey Kong": {
 image:"donkey_kong.png",
weight:"127",
weightClass:"Super Heavyweight",
archetype:"Heavyweight Grappler",
combos:["Cargo Throw extensions","Down Tilt → Back Air","Falling Up Air strings"],
killConfirms:["Cargo Back Throw near ledge","Giant Punch"],
oos:["Up B"],
recovery:"Long horizontal recovery but vulnerable.",
notes:["Excellent advantage state","Powerful cargo throw game","Combo food at high levels"]
},
"Link": {
image:"link.png",
weight:"104",
weightClass:"Heavyweight",
archetype:"Swordfighter/Zoner",
combos:["Bomb confirms","Nair → Grab","Boomerang extensions"],
killConfirms:["Remote Bomb","Up Smash","Forward Smash"],
oos:["Up B"],
recovery:"Remote Bomb recovery adds mixups.",
notes:["Versatile projectile game","Excellent nair","Strong ledge trapping"]
},
"Samus": {
image:"samus.png",
weight:"108",
weightClass:"Heavyweight",
archetype:"Zoner",
combos:["Down Throw → Fair","Charge Shot confirms","Up Air juggles"],
killConfirms:["Charge Shot","Back Air","Forward Air offstage"],
oos:["Up B (Frame 4)"],
recovery:"Excellent recovery with Bomb mixups.",
notes:["Powerful zoning","Excellent ledge trapping","Strong disadvantage escapes"]
},
"Dark Samus": {
  image: "dark_samus.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Yoshi": {
  image: "yoshi.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Kirby": {
  image: "kirby.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Fox": {
image:"fox.png",
weight:"77",
weightClass:"Lightweight",
archetype:"Rushdown",
combos:["Nair → Up Smash","Up Tilt strings","Dragdown Fair"],
killConfirms:["Nair → Up Smash","Back Air"],
oos:["Nair"],
recovery:"Fast but exploitable recovery.",
notes:["Extremely fast","Explosive advantage state","Can struggle to land"]
},
"Pikachu": {
  image: "pikachu.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Luigi": {
  image: "luigi.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ness": {
  image: "ness.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Jigglypuff": {
  image: "jigglypuff.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Peach": {
 image:"peach.png",
weight:"89",
weightClass:"Lightweight",
archetype:"Float Character",
combos:["Float Cancel strings","Down Tilt → Aerial","Turnip extensions"],
killConfirms:["Back Air","Forward Air","Edgeguards"],
oos:["Nair"],
recovery:"Float and Parasol provide excellent recovery.",
notes:["Exceptional combo game","High technical skill ceiling","Strong edgeguarding"]
},
"Daisy": {
  image: "daisy.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ice Climbers": {
  image: "ice_climbers.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Sheik": {
  image: "sheik.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Zelda": {
  image: "zelda.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Dr. Mario": {
  image: "dr_mario.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Pichu": {
  image: "pichu.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Falco": {
image:"falco.png",
weight:"82",
weightClass:"Lightweight",
archetype:"Combo Fighter",
combos:["Down Throw → Fair","Up Tilt strings","Dragdown Nair"],
killConfirms:["Back Air","Down Tilt → Back Air"],
oos:["Nair"],
recovery:"Long recovery distance but predictable.",
notes:["Excellent combo game","Strong anti-air tools","Can struggle landing"]
},
"Marth": {
image:"marth.png",
weight:"90",
weightClass:"Middleweight",
archetype:"Precision Swordfighter",
combos:["Fair strings","Up Air juggling","Nair pressure"],
killConfirms:["Tipper F-Smash","Tipper Back Air","Tipper Forward Tilt"],
oos:["Up B"],
recovery:"Reliable recovery with Dolphin Slash.",
notes:["Tipper mechanic is critical","Explosive kill power","Spacing focused"]
},
"Lucina": {
  image:"lucina.png",
weight:"90",
weightClass:"Middleweight",
archetype:"Fundamentals Swordfighter",
combos:["Falling Fair → Grab","Up Air juggles","Nair pressure"],
killConfirms:["Back Air","Edgeguards","Forward Smash read"],
oos:["Up B"],
recovery:"Reliable recovery with Dolphin Slash.",
notes:["Consistent sword hitboxes","Strong edgeguarding","Excellent neutral"]
},
"Young Link": {
  image: "young_link.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ganondorf": {
image:"ganondorf.png",
weight:"118",
weightClass:"Super Heavyweight",
archetype:"Heavyweight",
combos:["Down Throw → Nair","Dash Attack followups","Up Air strings"],
killConfirms:["Forward Smash","Back Air","Flame Choke reads"],
oos:["Nair"],
recovery:"Weak recovery distance.",
notes:["Kills absurdly early","Slow movement","Punishes mistakes hard"]
},
"Mewtwo": {
  image: "mewtwo.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Roy": {
 image:"roy.png",
weight:"95",
weightClass:"Middleweight",
archetype:"Rushdown Swordfighter",
combos:["Jab → Back Air","Nair → Fair","Down Tilt → Dash Attack"],
killConfirms:["Jab → Back Air","Side B sweetspot"],
oos:["Up B"],
recovery:"Recoveries can be vulnerable.",
notes:["Explosive damage output","Strong close-range sword attacks","Excellent pressure"]
},
"Chrom": {
image:"chrom.png",
weight:"95",
weightClass:"Middleweight",
archetype:"Rushdown Swordfighter",
combos:["Jab → Back Air","Nair → Fair","Up Air juggling"],
killConfirms:["Jab → Back Air","Forward Smash"],
oos:["Up B"],
recovery:"Powerful but exploitable recovery.",
notes:["Excellent damage output","Aggressive playstyle","Strong advantage state"]
},
"Mr. Game & Watch": {
  image: "mr_game_and_watch.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Meta Knight": {
  image: "meta_knight.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Pit": {
  image: "pit.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Dark Pit": {
  image: "dark_pit.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Zero Suit Samus": {
  image: "zero_suit_samus.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Wario": {
  image: "wario.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Snake": {
 image:"snake.png",
weight:"106",
weightClass:"Heavyweight",
archetype:"Trapper",
combos:["Grenade conversions","Down Throw → Tech Chase","Up Tilt anti-air"],
killConfirms:["Up Tilt","Back Air","C4 setups"],
oos:["Up Smash"],
recovery:"Cypher provides excellent recovery distance.",
notes:["Explosive ledge trapping","Grenades disrupt combos","Strong survivability"]
},
"Ike": {
  image: "ike.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Squirtle":{
image:"squirtle.png",
weight:"75",
weightClass:"Lightweight",
archetype:"Rushdown",
combos:["Down Throw → Fair","Up Tilt strings","Nair → Grab"],
killConfirms:["Up Smash","Edgeguarding","Back Air near ledge"],
oos:["Up Smash"],
recovery:"Excellent recovery with Waterfall.",
notes:[
"Fastest Pokémon",
"Strong combo game",
"Small hurtbox",
"Struggles to secure kills"
]
},

"Ivysaur":{
image:"ivysaur.png",
weight:"96",
weightClass:"Middleweight",
archetype:"Zoner",
combos:["Up Air juggles","Down Throw → Up Air","Razor Leaf extensions"],
killConfirms:["Up Air","Back Air","Down Air spike"],
oos:["Nair"],
recovery:"Long recovery with Vine Whip.",
notes:[
"Best juggling Pokémon",
"Excellent range",
"Powerful aerials",
"Strong kill power"
]
},

"Charizard":{
image:"charizard.png",
weight:"116",
weightClass:"Super Heavyweight",
archetype:"Heavyweight",
combos:["Nair → Grab","Up Throw → Up Air","Landing Fair"],
killConfirms:["Back Air","Up Smash","Flare Blitz"],
oos:["Up Smash"],
recovery:"Outstanding recovery with Fly.",
notes:[
"Heaviest Pokémon",
"Excellent survivability",
"Strong kill options",
"Can struggle against combos"
]
},
"Diddy Kong": {
image:"diddy_kong.png",
weight:"90",
weightClass:"Middleweight",
archetype:"Trickster",
combos:["Down Throw → Fair","Banana confirms","Nair strings"],
killConfirms:["Banana → Forward Smash","Back Air"],
oos:["Nair"],
recovery:"Excellent recovery with Rocketbarrel Boost.",
notes:["Banana Peel controls neutral","Excellent mobility","Strong item play"]
},
"Lucas": {
  image: "lucas.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Sonic": {
image:"sonic.png",
weight:"86",
weightClass:"Lightweight",
archetype:"Hit-and-Run",
combos:["Down Throw → Fair","Up Air strings","Spin Dash extensions"],
killConfirms:["Back Air near ledge","Forward Smash read"],
oos:["Nair"],
recovery:"Excellent recovery with Spring Jump.",
notes:["Fastest character in the game","Strong whiff punishing","Can time opponents out"]
},
"King Dedede": {
  image: "king_dedede.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Olimar": {
  image: "olimar.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Lucario": {
  image: "lucario.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"R.O.B.": {
  image: "rob.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Toon Link": {
  image: "toon_link.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Wolf": {
  image:"wolf.png",
weight:"92",
weightClass:"Middleweight",
archetype:"All-Rounder",
combos:["Falling Fair → Dash Attack","Nair → Grab","Down Throw → Dash Attack"],
killConfirms:["Back Air","Down Smash ledge trap"],
oos:["Nair"],
recovery:"Linear recovery that can be exploited.",
notes:["Excellent neutral","Powerful aerials","Strong ledge trapping"]
},
"Villager": {
  image: "villager.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Mega Man": {
  image: "mega_man.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Wii Fit Trainer": {
  image: "wii_fit_trainer.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Rosalina & Luma": {
  image: "rosalina_luma.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Little Mac": {
  image: "little_mac.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Greninja": {
  image: "greninja.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Palutena": {
 image:"palutena.png",
weight:"91",
weightClass:"Middleweight",
archetype:"All-Rounder",
combos:["Nair loops","Down Throw → Back Air","Up Air juggles"],
killConfirms:["Back Air","Dash Attack","Edgeguarding"],
oos:["Nair"],
recovery:"Teleport recovery is difficult to challenge.",
notes:["Excellent mobility","Strong aerial pressure","Excellent edgeguarding"]
},
"Pac-Mn": {
  image: "pac_man.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Robin": {
  image: "robin.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Shulk": {
  image: "shulk.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Bowser Jr.": {
  image: "bowser_jr.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Duck Hunt": {
  image: "duck_hunt.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ryu": {
  image: "ryu.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ken": {
  image: "ken.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Cloud": {
  image:"cloud.png",
weight:"100",
weightClass:"Middleweight",
archetype:"Swordfighter",
combos:["Landing Nair → Grab","Up Air juggles","Cross Slash extensions"],
killConfirms:["Back Air","Limit Cross Slash","Up Smash anti-air"],
oos:["Climhazzard (Frame 7)"],
recovery:"Limit recovery is strong, non-limit is exploitable.",
notes:["Excellent range","Strong juggling","Limit management is key"]
},
"Corrin": {
  image: "corrin.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Bayonetta": {
  image: "bayonetta.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Inkling": {
  image: "inkling.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Ridley": {
  image: "ridley.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Simon": {
  image: "simon.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Richter": {
  image: "richter.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"King K. Rool": {
image:"king_k_rool.png",
weight:"133",
weightClass:"Super Heavyweight",
archetype:"Heavyweight",
combos:["Down Throw tech chase","Nair pressure","Crown confirms"],
killConfirms:["Back Air","Forward Tilt","Blunderbuss setups"],
oos:["Neutral Air"],
recovery:"Excellent recovery with Propellerpack.",
notes:["Armor on many moves","Very heavy","Strong ledge trapping"]
},
"Isabelle": {
  image: "isabelle.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Incineroar": {
image:"incineroar.png",
weight:"116",
weightClass:"Super Heavyweight",
archetype:"Grappler",
combos:["Down Throw → Fair","Landing Nair","Revenge conversions"],
killConfirms:["Back Air","Lariat","Side B"],
oos:["Up Smash"],
recovery:"Limited recovery distance.",
notes:["Massive damage output","Revenge changes matchups","Very slow"]
},
"Piranha Plant": {
  image: "piranha_plant.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Joker": {
 image:"joker.png",
weight:"93",
weightClass:"Middleweight",
archetype:"Rushdown",
combos:["Down Throw → Fair","Dragdown Up Air extensions","Nair strings"],
killConfirms:["Arsene Back Air","Dragdown Up Air → Smash Attack"],
oos:["Nair","Back Air"],
recovery:"Excellent recovery with Grappling Hook and Arsene.",
notes:["Arsene dramatically changes kill power","Excellent mobility","Strong edgeguarding"]
},
"Hero": {
  image: "hero.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Banjo & Kazooie": {
  image: "banjo_and_kazooie.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Terry": {
  image: "terry.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Byleth": {
  image: "byleth.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Min Min": {
  image: "min_min.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Steve": {
 image:"steve.png",
weight:"92",
weightClass:"Middleweight",
archetype:"Trap/Zoner",
combos:["Up Tilt strings","Up Air ladders","Minecart extensions"],
killConfirms:["Minecart","Forward Smash","Anvil"],
oos:["Up Smash"],
recovery:"Extremely versatile recovery options.",
notes:["Resource management character","Dominant advantage state","Excellent ledge trapping"]
},
"Sephiroth": {
  image: "sephiroth.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Pyra": {
 image:"pyra.png",
weight:"92",
weightClass:"Middleweight",
archetype:"Power Swordfighter",
combos:["Down Tilt → Up Air","Landing Nair → Grab","Up Air juggling"],
killConfirms:["Back Air","Forward Smash","Up Smash"],
oos:["Up B"],
recovery:"Strong vertical recovery but limited horizontal distance.",
notes:[
"Primary stock closer",
"High damage output",
"Excellent kill power",
"Slower movement and frame data"
]
},

"Mythra":{
image:"mythra.png",
weight:"92",
weightClass:"Middleweight",
archetype:"Rushdown Swordfighter",
combos:["Nair → Nair","Up Air ladders","Down Throw → Fair"],
killConfirms:["Forward Smash read","Up Smash","Edgeguards"],
oos:["Up B"],
recovery:"Longer recovery distance than Pyra.",
notes:[
"Wins neutral frequently",
"Excellent mobility",
"Fast frame data",
"Relies on Pyra for early kills"
]
},

"Kazuya": {
 image:"kazuya.png",
weight:"113",
weightClass:"Heavyweight",
archetype:"Fighting Game Character",
combos:["Electric → Electric","Electric → Up Smash","Touch of Death strings"],
killConfirms:["Electric confirms","Rage Drive"],
oos:["Up B"],
recovery:"Strong vertical recovery.",
notes:["Devastating punish game","Touch of death potential","Weak disadvantage state"]
},
"Sora": {
image:"sora.png",
weight:"85",
weightClass:"Lightweight",
archetype:"Aerial Fighter",
combos:["Nair loops","Fair strings","Up Air ladders"],
killConfirms:["Back Air","Edgeguarding","Up Smash reads"],
oos:["Nair"],
recovery:"Outstanding recovery distance.",
notes:["Very floaty","Exceptional offstage game","Lightweight"]
},
"Mii Brawler": {
  image: "mii_brawler.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Mii Swordfighter": {
  image: "mii_swordfighter.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
},
"Mii Gunner": {
  image: "mii_gunner.png",
  weight: "TBD",
  weightClass: "TBD",
  archetype: "Varies",
  combos: ['Primary combo starter → follow-up', 'Bread and butter string'],
  oos: ["Best OOS option"],
  killConfirms: ["Common kill move, Ledge option"],
  recovery: "Add recovery notes here.",
  notes: ["Add character-specific notes."]
}
};
"Mii Brawler":{
image:"mii_brawler.png",
weight:"94",
weightClass:"Middleweight",
archetype:"Rushdown",
combos:["Down Throw → Up B","Nair → Fair","Up Air strings"],
killConfirms:["Thrupper","Back Air","Forward Smash"],
oos:["Up B"],
recovery:"Good recovery depending on specials selected.",
notes:[
"Fast close-range fighter",
"Strong combo game",
"Custom specials change playstyle",
"Excellent frame data"
]
},
